### PR TITLE
privacy policy

### PR DESCRIPTION
**Pull request by jack-han-115**

### CODE REVIEW

**Comment by ramishenouda** [comment]
Users should be able to add new lines to the privacy policy message.
currently adding a new line doesn't work... maybe consider using the HTML tag `pre`?
image

**Comment by jack-han-115** [comment]
@ramishenouda  plz check
image

**Comment by ramishenouda** [comment]
@jack-han-115 I'm not sure if this is how the privacy text is supposed to look/styled.. but we don't have a Figma design for it.
I will merge it and we can ask them later about what they think 😅

**Comment by ramishenouda** [comment]
The text is not aligned with the checkbox
image

The text is not in the middle
image

I think the height should be able to scale without a scrollbar, similar to the question description.
image

The user can't edit the privacy policy using the `ContentEditable` component once he edits it from the input `Privacy policy message` in the survey settings.

**Comment by kevin-foster-uk** [comment]
Text is still not aligned correctly:
Screenshot 2023-09-05 at 12 52 53

Also the main text content should be limited 4/6/8?? lines and should be scrollable, both in the center area and on the right.
Screenshot 2023-09-05 at 12 54 47

**Pull request merged**
